# https://stackoverflow.com/questions/43322033/create-database-on-docker-compose-startup
version: "3.9"
services:
  web:
    build:
      context: ./NMS-Cinema-UX
      dockerfile: DockerFile
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - "api"
      - "database"
  api:
    build:
      context: ./NmsCinemaApi
      dockerfile: DockerFile
    ports:
      - "8085:8085" 
    depends_on:
      - "database"
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "nmscinema"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "avocado"
    volumes:
        - ./init.sql:/data/application/init.sql


